/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import presentacion.administrador.MantenedorAlumno;

/**
 *
 * @author CesarLopez
 */
public class Admi_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Admi_Principal
     */
    public Admi_Principal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemCerrarAplicacion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAlumno = new javax.swing.JMenuItem();
        menuItemAnioAcademico = new javax.swing.JMenuItem();
        menuItemDocente = new javax.swing.JMenuItem();
        menuItemClase = new javax.swing.JMenuItem();
        menuItemCurso = new javax.swing.JMenuItem();
        menuItemEspecialidad = new javax.swing.JMenuItem();
        menuItemGrado = new javax.swing.JMenuItem();
        menuItemNivelEducacion = new javax.swing.JMenuItem();
        menuItemPeriodo = new javax.swing.JMenuItem();
        menuItemSeccion = new javax.swing.JMenuItem();
        menuItemTipoEvaluacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Administrador");

        jdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");

        menuItemInicio.setText("Inicio");
        jMenu1.add(menuItemInicio);

        menuItemCerrarSesion.setText("Cerrar Sesion");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCerrarSesion);

        menuItemCerrarAplicacion.setText("Cerrar Aplicacion");
        menuItemCerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarAplicacionActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCerrarAplicacion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gestionar");

        menuItemAlumno.setText("Alumno");
        menuItemAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlumnoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAlumno);

        menuItemAnioAcademico.setText("Año academico");
        menuItemAnioAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAnioAcademicoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAnioAcademico);

        menuItemDocente.setText("Docente");
        menuItemDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDocenteActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemDocente);

        menuItemClase.setText("Clase");
        jMenu2.add(menuItemClase);

        menuItemCurso.setText("Curso");
        menuItemCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCursoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCurso);

        menuItemEspecialidad.setText("Especialidad");
        menuItemEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspecialidadActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEspecialidad);

        menuItemGrado.setText("Grado");
        menuItemGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGradoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemGrado);

        menuItemNivelEducacion.setText("Nivel Educacion");
        menuItemNivelEducacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNivelEducacionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemNivelEducacion);

        menuItemPeriodo.setText("Periodo");
        menuItemPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPeriodoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemPeriodo);

        menuItemSeccion.setText("Seccion");
        menuItemSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeccionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSeccion);

        menuItemTipoEvaluacion.setText("Tipo de Evaluacion");
        menuItemTipoEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTipoEvaluacionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemTipoEvaluacion);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Matricula");

        jMenuItem4.setText("Matricula");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Accesos");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reporte");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayuda");

        jMenuItem1.setText("Acerca de");
        jMenu6.add(jMenuItem1);

        jMenuItem3.setText("Ayuda");
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login form = new Login(null, true);
        form.setVisible(true);
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemCerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarAplicacionActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemCerrarAplicacionActionPerformed

    private void menuItemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlumnoActionPerformed
        // TODO add your handling code here:
        MantenedorAlumno frm = new MantenedorAlumno();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuItemAlumnoActionPerformed

    private void menuItemAnioAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAnioAcademicoActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarAnioAcademico frm = new Admi_buscarAnioAcademico();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemAnioAcademicoActionPerformed

    private void menuItemDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDocenteActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarDocente frm = new Admi_buscarDocente();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemDocenteActionPerformed

    private void menuItemCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCursoActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarCurso frm = new Admi_buscarCurso();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemCursoActionPerformed

    private void menuItemEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspecialidadActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarEspecialidad frm = new Admi_buscarEspecialidad();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemEspecialidadActionPerformed

    private void menuItemGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGradoActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarGrado frm = new Admi_buscarGrado();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemGradoActionPerformed

    private void menuItemNivelEducacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNivelEducacionActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarNivelEducacion frm = new Admi_buscarNivelEducacion();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemNivelEducacionActionPerformed

    private void menuItemPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPeriodoActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarPeriodo frm = new Admi_buscarPeriodo();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemPeriodoActionPerformed

    private void menuItemSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeccionActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarSeccion frm = new Admi_buscarSeccion();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemSeccionActionPerformed

    private void menuItemTipoEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTipoEvaluacionActionPerformed
        // TODO add your handling code here:
        /*
        Admi_buscarTipoEvaluacion frm = new Admi_buscarTipoEvaluacion();
        jdpPrincipal.add(frm);
        frm.setVisible(true);
        */
    }//GEN-LAST:event_menuItemTipoEvaluacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admi_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem menuItemAlumno;
    private javax.swing.JMenuItem menuItemAnioAcademico;
    private javax.swing.JMenuItem menuItemCerrarAplicacion;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemClase;
    private javax.swing.JMenuItem menuItemCurso;
    private javax.swing.JMenuItem menuItemDocente;
    private javax.swing.JMenuItem menuItemEspecialidad;
    private javax.swing.JMenuItem menuItemGrado;
    private javax.swing.JMenuItem menuItemInicio;
    private javax.swing.JMenuItem menuItemNivelEducacion;
    private javax.swing.JMenuItem menuItemPeriodo;
    private javax.swing.JMenuItem menuItemSeccion;
    private javax.swing.JMenuItem menuItemTipoEvaluacion;
    // End of variables declaration//GEN-END:variables
}
