package presentacion.administrador;

import controlador.AlumnoJpaController;
import controlador.exceptions.IllegalOrphanException;
import controlador.exceptions.NonexistentEntityException;
import entidades.Alumno;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CesarLopez
 */
public class MantenedorAlumno extends javax.swing.JInternalFrame {

    private List<Alumno> listaDeAlumnos;
    private Alumno alumno;
    private AlumnoJpaController controladorAlumno = new AlumnoJpaController();
    
    public MantenedorAlumno() {
        initComponents();
        setLocation(300, 100);
        listarTodo();
        activarBotones(true, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboTipo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnNuevo = new javax.swing.JMenu();
        btnModificar = new javax.swing.JMenu();
        btnEliminar = new javax.swing.JMenu();

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "DNI", "Email" }));

        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumno);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnNuevo);

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEliminar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listarTodo() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre Completo");
        modelo.addColumn("DNI");

        listaDeAlumnos = controladorAlumno.findAlumnoEntities();
        for (Alumno alumno : listaDeAlumnos) {
            modelo.addRow(new String[]{
                alumno.getNombre() + ",   "
                + alumno.getApellidoPaterno() + "   "
                + alumno.getApellidoMaterno() + "   ",
                alumno.getDni()
            });
        }
        tblAlumno.setModel(modelo);
    }
    
    private void activarBotones(boolean a, boolean b, boolean c) {
        btnNuevo.setEnabled(a);
        btnModificar.setEnabled(b);
        btnEliminar.setEnabled(c);
    }
    
    
    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        // TODO add your handling code here:
        DatosAlumno form = new DatosAlumno(null, true);
        form.setVisible(true);
        listarTodo();
        activarBotones(true, false, false);
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
        if (btnModificar.isEnabled()) {
            DatosAlumno form = new DatosAlumno(null, true, alumno);
            form.setVisible(true);
            activarBotones(true, false, false);
            listarTodo();
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        //0=si  1=no    2=cancel
        
        if (btnEliminar.isEnabled()) {
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
           
            if (resp == 0) {
                
                try {
                    controladorAlumno.destroy(alumno.getId());
                    JOptionPane.showMessageDialog(this, "Eliminacion satisfactoria");
                } catch (IllegalOrphanException | NonexistentEntityException ex) {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar");
                }
                
                listarTodo();
                
            } else {
                JOptionPane.showMessageDialog(this, "Se cancelo su operacion");
            }
            activarBotones(true, false, false);
        }
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void tblAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnoMouseClicked
        // TODO add your handling code here:
        int fila = tblAlumno.getSelectedRow();
        if (fila != -1) {
            alumno = listaDeAlumnos.get(fila);
            activarBotones(true, true, true);
        }
        
        System.out.println("alumno.getId = " + alumno.getId());
        System.out.println("alumno.getNombre = " + alumno.getNombre());
        System.out.println("alumno.getIdUsuario = " + alumno.getEmail());
        
    }//GEN-LAST:event_tblAlumnoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        activarBotones(true, false, false);
        /*
        String valor = txtValor.getText();
        String tipo = cboTipo.getSelectedItem().toString();

        DefaultTableModel modelo = (DefaultTableModel) tblAlumno.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        listaDeAlumnos = servicio.buscar(tipo, valor);

        for (Alumno alumno : listaDeAlumnos) {
            modelo.addRow(new String[]{
                alumno.getNombre() + "",
                alumno.getApellidoPaterno() + "",
                alumno.getApellidoMaterno() + "",
                alumno.getDni() + "",});
        }
        tblAlumno.setModel(modelo);
        */
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenu btnEliminar;
    private javax.swing.JMenu btnModificar;
    private javax.swing.JMenu btnNuevo;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlumno;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
